'use strict';
const $=s=>document.querySelector(s),canvas=$('#world'),ctx=canvas.getContext('2d');
const imgs={};for(const n of ['forest','ara','ira','atlas','decor','level-2','level-3','level-4','level-5']){imgs[n]=new Image();imgs[n].src='assets/'+n+'.webp'}
let state='menu',page=0,W=innerWidth,H=innerHeight,DPR=Math.min(devicePixelRatio||1,2),last=0,time=0,pausedFrom='menu',heart=3,invuln=0,cooldown=0,pulse=0,toastTime=0,target=null,walk=false,face=1;
let levelIndex=0,marks=[],decorations=[],sparkles=[],stageFinished=false;
let sound=false,reduced=false;try{const s=JSON.parse(localStorage.getItem('ara-options')||'{}');sound=!!s.sound;reduced=!!s.reduced}catch{}document.body.classList.toggle('reduced',reduced);
const player={x:2,y:3},keys=new Set(),trees=[],bats=[];let audio;
function tone(f=500,d=.18){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.65,audio.currentTime+d);g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
function seed(n){let v=Math.sin(n*127.1+311.7)*43758.5453;return v-Math.floor(v)}
const levels=[
{name:'The Whispering Woods',size:20,scene:'forest',task:'walk',items:0,theme:['#53635b','#4c5c55','#59665a','#1b393b','#1e3b3b','#213f3c'],tint:'#254b4b',decor:7,bats:2,entry:'“Ira? It’s me. I brought a light.”',caption:'A ribbon, a rustle, and two very nosy bats.',outro:'A tiny bow is tied to the lantern gate. It points toward a glow in the trees.',joke:'“Ira, your directions are very… ribbon-y.”'},
{name:'Glowcap Glade',size:22,scene:'level-2',task:'glow',items:3,theme:['#6a5777','#63516e','#716080','#302d4d','#352c4d','#3b3451'],tint:'#50466b',decor:0,bats:2,entry:'“Are these mushrooms night-lights? Excellent.”',caption:'The mushrooms were asleep. Ara had a bright idea.',outro:'Three glowcaps stretch and shine. A trail of little ribbon scraps appears beside the brook.',joke:'“Thank you, mushrooms. Very illuminating.”'},
{name:'Puddlebrook Crossing',size:23,scene:'level-3',task:'collect',items:3,theme:['#7f8580','#737d77','#8b9188','#174f5e','#1e5a64','#226472'],tint:'#255f68',decor:1,bats:2,entry:'“Stepping stones. Not splashing stones. Got it.”',caption:'A brook, a bridge, and a frog with absolutely no advice.',outro:'Ara follows the last scrap across the brook. On the far bank, little stars wink between the branches.',joke:'“My paws are only a little bit soggy. A fashionable amount.”'},
{name:'Stargazer Hollow',size:24,scene:'level-4',task:'glow',items:3,theme:['#505f82','#475574','#5a678d','#1d294d','#233054','#26345b'],tint:'#33487a',decor:6,bats:3,entry:'“Excuse me, stars. Have you seen a pillow?”',caption:'Even the stars needed someone to leave a light on.',outro:'The sleepy lanterns blink awake. Beyond them, Ara spots a tiny cottage and a very familiar pink bow.',joke:'“Aha! Unless the cottage is wearing Ira’s bow…”'},
{name:'Pillowmoon Garden',size:25,scene:'level-5',task:'glow',items:2,theme:['#847866','#7a705e','#8e8370','#365348','#3a5a4d','#416254'],tint:'#5c6953',decor:4,bats:1,entry:'“Ira! Is that you? Please don’t be another cushion.”',caption:'Home was never very far from a sister’s hug.',outro:'Ira had followed a butterfly, lost her way, and waited beside the warm little cottage.',joke:'“I was hiding,” said Ira. “Just… a bit too successfully.”'}
];
function current(){return levels[levelIndex]}
function curve(x){return Math.sin(x*(.45+levelIndex*.025)+levelIndex*.6)*(1.3+levelIndex*.18)}
function pathY(x){return x+curve(x)}
function exitPoint(){return {x:current().size-3,y:pathY(current().size-3)}}
function buildLevel(){const l=current();trees.length=0;decorations.length=0;marks=[];sparkles=[];stageFinished=false;for(let i=0;i<l.items;i++){let x=5+i*(l.size-10)/Math.max(1,l.items-1);marks.push({x,y:pathY(x),lit:false,index:i})}let exit=exitPoint();for(let x=0;x<l.size;x++)for(let y=0;y<l.size;y++){let tx=x+.15+seed(x+y*36+levelIndex)*.25,ty=y+.15+seed(x*7+y+levelIndex)*.25,d=Math.abs(ty-pathY(tx));if(d>3.15&&seed(x*29+y+levelIndex*71)>.39&&Math.hypot(tx-exit.x,ty-exit.y)>2)trees.push({x:tx,y:ty,type:Math.floor(seed(x+y*14)*3),size:.8+seed(x*39+y)*.4})}for(let x=3;x<l.size-2;x+=2.8){decorations.push({x,y:pathY(x)+2.6,type:l.decor,size:.8+seed(x+levelIndex)*.3});decorations.push({x:x+.6,y:pathY(x)-2.6,type:levelIndex===4?4:l.decor,size:.7+seed(x+15)*.4})}bats.length=0;for(let i=0;i<l.bats;i++){let x=6+i*(l.size-12)/Math.max(1,l.bats-1);bats.push({x,y:pathY(x)+.4,homeX:x,homeY:pathY(x)+.4,fear:0,phase:i*2})}}
function objective(){let done=marks.filter(m=>m.lit).length;$('#hudChapter').textContent='CHAPTER '+(levelIndex+1)+' OF 5';$('#hudTitle').textContent=current().name;$('#objective').textContent=done<marks.length?(levelIndex===2?'Follow the ribbon scraps':levelIndex===1?'Wake the glowcaps':'Light the sleepy lanterns')+' · '+done+' / '+marks.length:(levelIndex===4?'Find Ira beside the little cottage.':'Follow the path to the lantern gate.');$('#journey').textContent=levels.map((_,i)=>i<levelIndex?'✦':i===levelIndex?'✧':'·').join('  ')}
const stories=[
{title:'The suspiciously giggly cushion.',caption:'One last game before bedtime.',text:'Ira was very good at being a pillow. Being a quiet pillow? A little trickier.',bubble:'Ready or not, here I come!',reply:'You can’t see me. I’m a cushion.',replySpeaker:'Ira',footnote:'A cushion with a very obvious bow.',word:'hee hee!',scene:'assets/comic-1.webp',alt:'Ara counts with her eyes covered while Ira peeks out from behind a tiny cushion in their cozy bedroom.'},
{title:'One sister, suddenly missing.',caption:'Then the giggling stopped.',text:'No Ira. Just an open window, a fluttering ribbon… and a very unhelpful teacup.',bubble:'Oh no! Ira’s missing!',reply:'Not in the teacup. Good to know.',replySpeaker:'Ara, checking everywhere',footnote:'Even excellent detectives start small.',word:'…Ira?',scene:'assets/comic-2.webp',alt:'Ara searches beneath an empty teacup as Ira’s ribbon flutters through the open bedroom window.'},
{title:'Brave. Mostly brave. Brave-ish.',caption:'A little light. A big deep breath.',text:'Ara followed the ribbon into the woods. Finding her sister mattered more than a few spooky shadows.',bubble:'Hold on, Ira. I’m coming!',reply:'Dear woods: please use your indoor voice.',replySpeaker:'Ara, politely',footnote:'Very small panda. Very big heart.',word:'gulp.',scene:'assets/comic-3.webp',alt:'Ara holds a warm glowing lantern at the edge of the moonlit woods while a little purple bat peeks down.'}
];
function showMenu(){stageFinished=false;state='menu';$('#menu').classList.remove('hidden');$('#comic').classList.add('hidden');$('#hud').classList.add('hidden');closeDialog();keys.clear();target=null}
function comic(){state='comic';$('#menu').classList.add('hidden');$('#comic').classList.remove('hidden');const s=stories[page];$('#panelTitle').textContent=s.title;$('#panelText').textContent=s.text;$('#caption').textContent=s.caption;$('#speaker').textContent='Ara';$('#bubble').textContent=s.bubble;$('#replySpeaker').textContent=s.replySpeaker;$('#replyBubble').textContent=s.reply;$('#footnote').textContent=s.footnote;$('#soundWord').textContent=s.word;$('#pageNum').textContent='OUR STORY · '+(page+1)+' OF 3';$('#next').textContent=page===2?'Into the woods!':'Turn the page';$('#previous').disabled=page===0;$('#comicAra').style.display='none';$('#comicIra').style.display='none';$('#comicArt').style.backgroundImage='url("'+s.scene+'")';$('#comicArt').setAttribute('aria-label',s.alt);$('#comicArt').dataset.panel=page;$('#dots').innerHTML=stories.map((_,i)=>'<i class="'+(i===page?'on':'')+'" aria-label="Page '+(i+1)+(i===page?', current':'')+'"></i>').join('');tone(660)}
$('#previous').onclick=()=>{if(page>0){page--;comic()}};
$('#start').onclick=()=>{page=0;comic()};$('#next').onclick=()=>{if(page<2){page++;comic()}else begin()};$('#skip').onclick=begin;
function begin(){startLevel(0)}
function startLevel(index){levelIndex=index;buildLevel();state='play';player.x=2;player.y=pathY(2);heart=3;invuln=0;cooldown=0;pulse=0;target=null;keys.clear();$('#comic').classList.add('hidden');$('#menu').classList.add('hidden');$('#hud').classList.remove('hidden');closeDialog();hearts();objective();toast(current().entry,5)}
function hearts(){$('#hearts').textContent=Array.from({length:3},(_,i)=>i<heart?'♥':'♡').join(' ');$('#hearts').ariaLabel=heart+' hearts remaining'}
function toast(s,d=3){$('#toast').textContent=s;$('#toast').classList.add('on');toastTime=d}
function modal(title,body,actions,eyebrow){pausedFrom=state;state='dialog';keys.clear();target=null;$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=body;$('#dialogEyebrow').textContent=eyebrow||'A MOMENT BY THE MOONLIGHT';$('#dialogActions').innerHTML='';for(const a of actions){let b=document.createElement('button');b.textContent=a.text;if(a.primary)b.className='primary';b.onclick=a.fn;$('#dialogActions').append(b)}$('#dialog').classList.remove('hidden');$('#dialogActions button')?.focus()}
function closeDialog(){$('#dialog').classList.add('hidden')}
function resume(){if(stageFinished){return}if(pausedFrom==='menu'){showMenu();return}state=pausedFrom;closeDialog()}
$('#options').onclick=()=>{modal('Make yourself at home.','<label class="setting">Lantern sounds<input id="snd" type="checkbox" '+(sound?'checked':'')+'></label><label class="setting">Gentler motion<input id="motion" type="checkbox" '+(reduced?'checked':'')+'></label><p>Move with WASD or the arrow keys. Tap a spot on the path to walk there. Space makes your lantern glow.</p>',[{text:'Back',fn:resume,primary:true}]);$('#snd').onchange=e=>{sound=e.target.checked;save();tone()};$('#motion').onchange=e=>{reduced=e.target.checked;document.body.classList.toggle('reduced',reduced);save()}};
function save(){try{localStorage.setItem('ara-options',JSON.stringify({sound,reduced}))}catch{}}
$('#credits').onclick=()=>modal('Two sisters. One adventure.','<p>Starring Ara the Panda and Ira the Pillowcase.</p><p>Inspired by your original character designs. A tiny, moonlit story about kindness, courage, and finding your way home.</p>',[{text:'Back',fn:resume,primary:true}],'THE OPENING CREDITS');
function pause(){if(state!=='play')return;modal('A little breather.','<p>The woods can wait. Your lantern is still glowing.</p>',[{text:'Keep adventuring',primary:true,fn:resume},{text:'Return to title',fn:showMenu}])}$('#pause').onclick=pause;
function glow(){if(state!=='play'||cooldown>0)return;pulse=.85;cooldown=2.6;for(const m of marks)if(!m.lit&&current().task==='glow'&&Math.hypot(m.x-player.x,m.y-player.y)<2.5){m.lit=true;sparkles.push({x:m.x,y:m.y,life:1});toast(levelIndex===1?'“Good morning… or good night, mushroom!”':'“There. Much less spooky.”',2.5);objective()}for(const b of bats)if(Math.hypot(b.x-player.x,b.y-player.y)<3.5){b.fear=3;toast('Just a little light. Off you flutter!',2)}tone(850,.5)}$('#glowTouch').onclick=glow;
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(state==='play')pause();else if(state==='dialog')resume();return}if(state==='comic'&&(e.code==='Space'||e.code==='Enter')){$('#next').click();return}if(state==='play'){keys.add(e.code);target=null;if(e.code==='Space')glow()}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();if(state==='play')pause()});
for(const b of document.querySelectorAll('[data-dir]')){let k={up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight'}[b.dataset.dir];b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(k);target=null};b.onpointerup=b.onpointercancel=()=>keys.delete(k)}
let tile=55,camera={x:0,y:0};function project(x,y){return{x:(x-y)*tile+camera.x,y:(x+y)*tile*.49+camera.y}}function unproject(x,y){let a=(x-camera.x)/tile,b=(y-camera.y)/(tile*.49);return{x:(a+b)/2,y:(b-a)/2}};
canvas.addEventListener('pointerdown',e=>{if(state!=='play')return;target=unproject(e.clientX,e.clientY)});
function blocked(x,y){if(x<.5||y<.5||x>current().size-1||y>current().size-1)return true;return trees.some(t=>Math.hypot(t.x-x,t.y-y)<.57)}
function move(dx,dy){if(!blocked(player.x+dx,player.y))player.x+=dx;if(!blocked(player.x,player.y+dy))player.y+=dy}
function update(dt){time+=dt;if(state!=='play')return;invuln=Math.max(0,invuln-dt);cooldown=Math.max(0,cooldown-dt);pulse=Math.max(0,pulse-dt);toastTime-=dt;if(toastTime<=0)$('#toast').classList.remove('on');let sx=0,sy=0;if(keys.has('KeyW')||keys.has('ArrowUp'))sy--;if(keys.has('KeyS')||keys.has('ArrowDown'))sy++;if(keys.has('KeyA')||keys.has('ArrowLeft'))sx--;if(keys.has('KeyD')||keys.has('ArrowRight'))sx++;let dx=(sx+sy)*.707,dy=(sy-sx)*.707;if(target&&!sx&&!sy){dx=target.x-player.x;dy=target.y-player.y;if(Math.hypot(dx,dy)<.12){target=null;dx=dy=0}}let len=Math.hypot(dx,dy);walk=len>.05;if(walk){dx/=len;dy/=len;face=dx-dy>=0?1:-1;let ox=player.x,oy=player.y;move(dx*dt*2.3,dy*dt*2.3);if(target&&Math.hypot(ox-player.x,oy-player.y)<.001){target=null;toast('A crooked tree! Try the moonlit path.',2)}}for(const b of bats){let dist=Math.hypot(b.x-player.x,b.y-player.y);b.fear=Math.max(0,b.fear-dt);let tx=b.homeX+Math.sin(time*.8+b.phase)*.9,ty=b.homeY+Math.cos(time*.65+b.phase)*.9;if(dist<3&&!b.fear){tx=player.x;ty=player.y}if(b.fear){tx=b.homeX+(b.x-player.x)*2;ty=b.homeY+(b.y-player.y)*2}let nx=tx-b.x,ny=ty-b.y,l=Math.hypot(nx,ny);if(l>.05){b.x+=nx/l*dt*(b.fear?2:dist<3?1.2:.6);b.y+=ny/l*dt*(b.fear?2:dist<3?1.2:.6)}if(dist<.6&&!invuln&&!b.fear){heart--;hearts();invuln=2.2;b.fear=2;toast('Oops! A fluttery bump. Space to shoo the bats.',3);tone(240);if(heart<=0){player.x=2;player.y=pathY(2);heart=3;hearts();toast('Take a breath. Let’s try the trail again.',4)}}}
for(const m of marks)if(!m.lit&&current().task==='collect'&&Math.hypot(player.x-m.x,player.y-m.y)<.85){m.lit=true;toast('“Another ribbon scrap! Ira was here.”',2.5);objective();tone(720)}for(const f of sparkles)f.life-=dt;sparkles=sparkles.filter(f=>f.life>0);
$('#glowStatus').textContent=cooldown>0?'✧ Recharging… '+Math.ceil(cooldown)+'s':'✧ Lantern ready';let ex=exitPoint();if(Math.hypot(player.x-ex.x,player.y-ex.y)<1.1){if(marks.every(m=>m.lit))complete();else if(toastTime<=0)toast(current().task==='collect'?'A few ribbon scraps are still on the path.':'The path needs a little more light. Glow near the marked spots.',3)}}
function complete(){if(stageFinished)return;stageFinished=true;tone(880,.5);const l=current();if(levelIndex<4){const next=levels[levelIndex+1];modal(next.name,'<img class="chapter-art" src="assets/'+next.scene+'.webp" alt="'+next.name+'"><p class="chapter-caption">'+next.caption+'</p><p>'+l.outro+'</p><p class="chapter-joke">'+l.joke+'</p>',[{text:'On to chapter '+(levelIndex+2),primary:true,fn:()=>startLevel(levelIndex+1)},{text:'Return to title',fn:showMenu}],'CHAPTER '+(levelIndex+1)+' COMPLETE · FOUR PAWS FORWARD')}else{modal('Found you, little sister.','<div class="reunion" style="background-image:url(assets/level-5.webp)"><img src="assets/ara.webp" alt="Ara"><img src="assets/ira.webp" alt="Ira"></div><p class="chapter-caption">Five little chapters. One very big hug.</p><p>'+l.outro+'</p><p class="chapter-joke">'+l.joke+'</p><p>“Next time,” Ara smiled, “we hide somewhere with biscuits.”</p>',[{text:'Adventure again',primary:true,fn:begin},{text:'Return to title',fn:showMenu}],'IRA FOUND · THE END')}pausedFrom='play'}

function drawImage(img,x,y,w,h){if(img.complete&&img.naturalWidth)ctx.drawImage(img,x,y,w,h)}
function cover(img){if(!img.naturalWidth)return;let s=Math.max(W/img.width,H/img.height);ctx.drawImage(img,(W-img.width*s)/2,(H-img.height*s)/2,img.width*s,img.height*s)}
// Atlas source rectangles are set after the artwork is integrated.
const atlasRects={trees:[[0,0,450,602],[450,0,370,605],[820,0,400,613]],bats:[[1090,185,446,320],[20,605,430,390]],lantern:[575,604,228,405],ribbon:[934,655,590,355]};
function sprite(rect,x,y,w,h){let im=imgs.atlas;if(im.complete&&im.naturalWidth)ctx.drawImage(im,rect[0]*im.naturalWidth/1536,rect[1]*im.naturalHeight/1024,rect[2]*im.naturalWidth/1536,rect[3]*im.naturalHeight/1024,x,y,w,h)}
function diamond(x,y,fill){const p=project(x,y);ctx.fillStyle=fill;ctx.beginPath();ctx.moveTo(p.x,p.y-tile*.49);ctx.lineTo(p.x+tile,p.y);ctx.lineTo(p.x,p.y+tile*.49);ctx.lineTo(p.x-tile,p.y);ctx.closePath();ctx.fill()}
const decorRects=[[0,0,385,512],[384,125,405,375],[790,175,435,345],[1230,35,305,480],[0,550,390,474],[385,540,460,450],[870,540,270,470],[1190,560,346,440]];
function decoration(type,x,y,w,h){let im=imgs.decor;if(im.complete&&im.naturalWidth){const r=decorRects[type],sx=im.naturalWidth/1536,sy=im.naturalHeight/1024;ctx.drawImage(im,r[0]*sx,r[1]*sy,r[2]*sx,r[3]*sy,x,y,w,h)}}
function aura(x,y,r,color){let a=ctx.createRadialGradient(x,y,2,x,y,r);a.addColorStop(0,color);a.addColorStop(1,color.slice(0,7)+'00');ctx.fillStyle=a;ctx.fillRect(x-r,y-r,r*2,r*2)}
function render(){ctx.clearRect(0,0,W,H);if(state==='menu'||state==='comic'||(state==='dialog'&&pausedFrom==='menu')){cover(imgs.forest);if(!imgs.forest.naturalWidth){ctx.fillStyle='#142a32';ctx.fillRect(0,0,W,H)}fireflies();return}
const l=current(),n=l.size;ctx.fillStyle='#081721';ctx.fillRect(0,0,W,H);ctx.globalAlpha=.42;cover(imgs[l.scene]);ctx.globalAlpha=1;tile=W<700?39:54;camera.x=W*.5-(player.x-player.y)*tile;camera.y=H*.53-(player.x+player.y)*tile*.49;let g=ctx.createRadialGradient(W*.5,H*.5,20,W*.5,H*.5,W*.75);g.addColorStop(0,l.tint+'66');g.addColorStop(1,'#081721bb');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
for(let sum=0;sum<n*2;sum++)for(let x=0;x<n;x++){let y=sum-x;if(y<0||y>=n)continue;let p=project(x,y);if(p.x<-tile||p.x>W+tile||p.y<-tile||p.y>H+tile)continue;let trail=Math.abs(y-pathY(x))<2;ctx.globalAlpha=trail?.94:.73;diamond(x,y,l.theme[(trail?0:3)+Math.floor(seed(x*43+y)*3)]);ctx.globalAlpha=1;ctx.fillStyle=trail?'#c4bd9138':'#9abbaf20';for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(p.x+(seed(x*87+y+i)-.5)*tile,p.y+(seed(x+y*37+i)-.5)*tile*.5,2.5,1,0,0,7);ctx.fill()}if(levelIndex===2&&!trail){ctx.strokeStyle='#8ed9d533';ctx.beginPath();ctx.ellipse(p.x,p.y+Math.sin(time+x)*2,18,4,0,0,7);ctx.stroke()}}
if(levelIndex===2){let bp=project(11,pathY(11));decoration(2,bp.x-100,bp.y-70,200,130)}
const ex=exitPoint(),gate=project(ex.x,ex.y),ready=marks.every(m=>m.lit);aura(gate.x,gate.y-35,100,ready?'#f6d69077':'#9bbfe433');if(levelIndex===4){decoration(5,gate.x-115,gate.y-190,230,215);drawImage(imgs.ira,gate.x+18,gate.y-61+(reduced?0:Math.sin(time*2)*2),53,62)}else{ctx.strokeStyle=ready?'#c5dcc0':'#687f84';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(gate.x-35,gate.y+4);ctx.lineTo(gate.x-35,gate.y-80);ctx.quadraticCurveTo(gate.x,gate.y-115,gate.x+35,gate.y-80);ctx.lineTo(gate.x+35,gate.y+4);ctx.stroke();sprite(atlasRects.lantern,gate.x-24,gate.y-97,48,65);sprite(atlasRects.ribbon,gate.x+12,gate.y-12,45,27)}ctx.fillStyle='#ecdfbd';ctx.font='italic 15px Georgia';ctx.textAlign='center';ctx.fillText(levelIndex===4?'Ira’s little hiding place':ready?'The way onward':'A little light will open the way',gate.x,gate.y-(levelIndex===4?210:124));
const ents=trees.map(t=>({depth:t.x+t.y,kind:'tree',t}));decorations.forEach(t=>ents.push({depth:t.x+t.y,kind:'decor',t}));marks.forEach(t=>ents.push({depth:t.x+t.y,kind:'mark',t}));ents.push({depth:player.x+player.y,kind:'player'});bats.forEach(b=>ents.push({depth:b.x+b.y,kind:'bat',b}));ents.sort((a,b)=>a.depth-b.depth);for(const e of ents){if(e.kind==='tree'){let t=e.t,p=project(t.x,t.y),h=tile*3.3*t.size,w=h*.68;if(p.x<-w||p.x>W+w||p.y<-20||p.y>H+h)continue;let pp=project(player.x,player.y);ctx.globalAlpha=p.y>pp.y&&Math.abs(p.x-pp.x)<w*.48&&p.y-pp.y<h*.8?.22:1;sprite(atlasRects.trees[t.type],p.x-w/2,p.y-h,w,h);ctx.globalAlpha=1}else if(e.kind==='decor'){let t=e.t,p=project(t.x,t.y),h=tile*1.6*t.size;if(p.x<-h||p.x>W+h||p.y<0||p.y>H+h)continue;decoration(t.type,p.x-h*.45,p.y-h,h*.9,h)}else if(e.kind==='mark'){let t=e.t,p=project(t.x,t.y);if(t.lit&&l.task==='collect')continue;aura(p.x,p.y-24,t.lit?70:45,t.lit?'#ffdd9577':'#baded144');if(l.task==='collect'){sprite(atlasRects.ribbon,p.x-24,p.y-36,48,29);ctx.fillStyle='#ffe0b5';ctx.font='14px Georgia';ctx.fillText('✧',p.x,p.y-45)}else{decoration(levelIndex===1?0:3,p.x-35,p.y-88,70,93);ctx.fillStyle=t.lit?'#fee1a1':'#b6ded0';ctx.font='12px system-ui';ctx.fillText(t.lit?'Awake!':'Glow nearby',p.x,p.y-99)}}else if(e.kind==='bat'){let b=e.b,p=project(b.x,b.y);ctx.fillStyle='#0003';ctx.beginPath();ctx.ellipse(p.x,p.y,15,5,0,0,7);ctx.fill();sprite(atlasRects.bats[reduced?0:Math.floor(time*8+b.phase)%2],p.x-34,p.y-68+(reduced?0:Math.sin(time*4+b.phase)*5),68,64)}else{let p=project(player.x,player.y);ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(p.x,p.y,22,8,0,0,7);ctx.fill();if(pulse>0){ctx.strokeStyle='#edd397'+Math.floor(pulse/.85*200).toString(16).padStart(2,'0');ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(p.x,p.y,35+(1-pulse/.85)*140,20+(1-pulse/.85)*70,0,0,7);ctx.stroke()}aura(p.x,p.y-30,95,'#efd39135');ctx.save();ctx.translate(p.x,p.y-(walk&&!reduced?Math.abs(Math.sin(time*11))*5:0));ctx.scale(face,1);if(invuln&&Math.floor(time*12)%2)ctx.globalAlpha=.5;ctx.rotate(walk&&!reduced?Math.sin(time*11)*.055:0);drawImage(imgs.ara,-35,-94,70,98);ctx.restore();sprite(atlasRects.lantern,p.x+17,p.y-47,26,36)}}
for(const f of sparkles){let p=project(f.x,f.y);ctx.fillStyle='#ffe8a6';for(let i=0;i<6;i++){ctx.font='19px Georgia';ctx.fillText('✧',p.x+Math.cos(i)*35*(1-f.life),p.y-35-Math.sin(i)*40*(1-f.life))}}if(target){let p=project(target.x,target.y);ctx.strokeStyle='#efd79caa';ctx.beginPath();ctx.ellipse(p.x,p.y,12,6,0,0,7);ctx.stroke()}fireflies();if(levelIndex===3){ctx.fillStyle='#d2d8ff88';ctx.font='14px Georgia';for(let i=0;i<12;i++)ctx.fillText('✧',seed(i*41)*W,(seed(i*9)*H+time*(reduced?0:7))%H)}if(levelIndex===4){ctx.fillStyle='#edb5bc88';for(let i=0;i<14;i++){ctx.beginPath();ctx.ellipse(seed(i*32)*W+Math.sin(time*.4+i)*10,(seed(i*11)*H+time*(reduced?0:12))%H,4,2,i,0,7);ctx.fill()}}ctx.fillStyle='#a7c4b716';for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(W*.5+(reduced?0:Math.sin(time*.1+i)*130),H*.3+i*160,W*.65,14,0,0,7);ctx.fill()}}
function fireflies(){for(let i=0;i<32;i++){let x=seed(i*7)*W+(reduced?0:Math.sin(time*.4+i)*22),y=seed(i*23+5)*H+(reduced?0:Math.cos(time*.3+i)*12);ctx.fillStyle='rgba(228,211,144,'+(.15+Math.sin(time*1.7+i)*.12)+')';ctx.beginPath();ctx.arc(x,y,1.5,0,7);ctx.fill()}}
function loop(ts){let dt=Math.min((ts-last)/1000,.04);last=ts;update(dt);render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
