'use strict';
const $=s=>document.querySelector(s),canvas=$('#world'),ctx=canvas.getContext('2d');
const imgs={};for(const n of ['forest','ara','ira','atlas']){imgs[n]=new Image();imgs[n].src='assets/'+n+'.webp'}
let state='menu',page=0,W=innerWidth,H=innerHeight,DPR=Math.min(devicePixelRatio||1,2),last=0,time=0,pausedFrom='menu',heart=3,invuln=0,cooldown=0,pulse=0,toastTime=0,target=null,walk=false,face=1;
let sound=false,reduced=false;try{const s=JSON.parse(localStorage.getItem('ara-options')||'{}');sound=!!s.sound;reduced=!!s.reduced}catch{}document.body.classList.toggle('reduced',reduced);
const player={x:2,y:3},keys=new Set(),trees=[],bats=[];let audio;
function tone(f=500,d=.18){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.65,audio.currentTime+d);g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
function seed(n){let v=Math.sin(n*127.1+311.7)*43758.5453;return v-Math.floor(v)}
for(let x=0;x<20;x++)for(let y=0;y<20;y++){let d=y-x-1.3*Math.sin(x*.45);if(Math.abs(d)>2.7&&seed(x*29+y)>.34)trees.push({x:x+.1+seed(x+y*36)*.4,y:y+.1+seed(x*7+y)*.4,type:Math.floor(seed(x+y*14)*3),size:.85+seed(x*39+y)*.35})}
const stories=[
{title:'The suspiciously giggly cushion.',caption:'One last game before bedtime.',text:'Ira was very good at being a pillow. Being a quiet pillow? A little trickier.',bubble:'Ready or not, here I come!',reply:'You can’t see me. I’m a cushion.',replySpeaker:'Ira',footnote:'A cushion with a very obvious bow.',word:'hee hee!',scene:'assets/comic-1.webp',alt:'Ara counts with her eyes covered while Ira peeks out from behind a tiny cushion in their cozy bedroom.'},
{title:'One sister, suddenly missing.',caption:'Then the giggling stopped.',text:'No Ira. Just an open window, a fluttering ribbon… and a very unhelpful teacup.',bubble:'Oh no! Ira’s missing!',reply:'Not in the teacup. Good to know.',replySpeaker:'Ara, checking everywhere',footnote:'Even excellent detectives start small.',word:'…Ira?',scene:'assets/comic-2.webp',alt:'Ara searches beneath an empty teacup as Ira’s ribbon flutters through the open bedroom window.'},
{title:'Brave. Mostly brave. Brave-ish.',caption:'A little light. A big deep breath.',text:'Ara followed the ribbon into the woods. Finding her sister mattered more than a few spooky shadows.',bubble:'Hold on, Ira. I’m coming!',reply:'Dear woods: please use your indoor voice.',replySpeaker:'Ara, politely',footnote:'Very small panda. Very big heart.',word:'gulp.',scene:'assets/comic-3.webp',alt:'Ara holds a warm glowing lantern at the edge of the moonlit woods while a little purple bat peeks down.'}
];
function showMenu(){state='menu';$('#menu').classList.remove('hidden');$('#comic').classList.add('hidden');$('#hud').classList.add('hidden');closeDialog();keys.clear();target=null}
function comic(){state='comic';$('#menu').classList.add('hidden');$('#comic').classList.remove('hidden');const s=stories[page];$('#panelTitle').textContent=s.title;$('#panelText').textContent=s.text;$('#caption').textContent=s.caption;$('#speaker').textContent='Ara';$('#bubble').textContent=s.bubble;$('#replySpeaker').textContent=s.replySpeaker;$('#replyBubble').textContent=s.reply;$('#footnote').textContent=s.footnote;$('#soundWord').textContent=s.word;$('#pageNum').textContent='OUR STORY · '+(page+1)+' OF 3';$('#next').textContent=page===2?'Into the woods!':'Turn the page';$('#previous').disabled=page===0;$('#comicAra').style.display='none';$('#comicIra').style.display='none';$('#comicArt').style.backgroundImage='url("'+s.scene+'")';$('#comicArt').setAttribute('aria-label',s.alt);$('#comicArt').dataset.panel=page;$('#dots').innerHTML=stories.map((_,i)=>'<i class="'+(i===page?'on':'')+'" aria-label="Page '+(i+1)+(i===page?', current':'')+'"></i>').join('');tone(660)}
$('#previous').onclick=()=>{if(page>0){page--;comic()}};
$('#start').onclick=()=>{page=0;comic()};$('#next').onclick=()=>{if(page<2){page++;comic()}else begin()};$('#skip').onclick=begin;
function begin(){state='play';player.x=2;player.y=3;heart=3;invuln=0;cooldown=0;pulse=0;target=null;keys.clear();bats.splice(0,bats.length,...[{x:7,y:8,homeX:7,homeY:8,fear:0,phase:0},{x:13,y:12,homeX:13,homeY:12,fear:0,phase:2}]);$('#comic').classList.add('hidden');$('#menu').classList.add('hidden');$('#hud').classList.remove('hidden');closeDialog();hearts();toast('“Ira? It’s me. I brought a light.”',5)}
function hearts(){$('#hearts').textContent=Array.from({length:3},(_,i)=>i<heart?'♥':'♡').join(' ');$('#hearts').ariaLabel=heart+' hearts remaining'}
function toast(s,d=3){$('#toast').textContent=s;$('#toast').classList.add('on');toastTime=d}
function modal(title,body,actions,eyebrow){pausedFrom=state;state='dialog';keys.clear();target=null;$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=body;$('#dialogEyebrow').textContent=eyebrow||'A MOMENT BY THE MOONLIGHT';$('#dialogActions').innerHTML='';for(const a of actions){let b=document.createElement('button');b.textContent=a.text;if(a.primary)b.className='primary';b.onclick=a.fn;$('#dialogActions').append(b)}$('#dialog').classList.remove('hidden');$('#dialogActions button')?.focus()}
function closeDialog(){$('#dialog').classList.add('hidden')}
function resume(){if(pausedFrom==='menu'){showMenu();return}state=pausedFrom;closeDialog()}
$('#options').onclick=()=>{modal('Make yourself at home.','<label class="setting">Lantern sounds<input id="snd" type="checkbox" '+(sound?'checked':'')+'></label><label class="setting">Gentler motion<input id="motion" type="checkbox" '+(reduced?'checked':'')+'></label><p>Move with WASD or the arrow keys. Tap a spot on the path to walk there. Space makes your lantern glow.</p>',[{text:'Back',fn:resume,primary:true}]);$('#snd').onchange=e=>{sound=e.target.checked;save();tone()};$('#motion').onchange=e=>{reduced=e.target.checked;document.body.classList.toggle('reduced',reduced);save()}};
function save(){try{localStorage.setItem('ara-options',JSON.stringify({sound,reduced}))}catch{}}
$('#credits').onclick=()=>modal('Two sisters. One adventure.','<p>Starring Ara the Panda and Ira the Pillowcase.</p><p>Inspired by your original character designs. A tiny, moonlit story about kindness, courage, and finding your way home.</p>',[{text:'Back',fn:resume,primary:true}],'THE OPENING CREDITS');
function pause(){if(state!=='play')return;modal('A little breather.','<p>The woods can wait. Your lantern is still glowing.</p>',[{text:'Keep adventuring',primary:true,fn:resume},{text:'Return to title',fn:showMenu}])}$('#pause').onclick=pause;
function glow(){if(state!=='play'||cooldown>0)return;pulse=.85;cooldown=3.2;for(const b of bats)if(Math.hypot(b.x-player.x,b.y-player.y)<3.5){b.fear=3;toast('Just a little light. Off you flutter!',2)}tone(850,.5)}$('#glowTouch').onclick=glow;
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(state==='play')pause();else if(state==='dialog')resume();return}if(state==='comic'&&(e.code==='Space'||e.code==='Enter')){$('#next').click();return}if(state==='play'){keys.add(e.code);target=null;if(e.code==='Space')glow()}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();if(state==='play')pause()});
for(const b of document.querySelectorAll('[data-dir]')){let k={up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight'}[b.dataset.dir];b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(k);target=null};b.onpointerup=b.onpointercancel=()=>keys.delete(k)}
let tile=55,camera={x:0,y:0};function project(x,y){return{x:(x-y)*tile+camera.x,y:(x+y)*tile*.49+camera.y}}function unproject(x,y){let a=(x-camera.x)/tile,b=(y-camera.y)/(tile*.49);return{x:(a+b)/2,y:(b-a)/2}};
canvas.addEventListener('pointerdown',e=>{if(state!=='play')return;target=unproject(e.clientX,e.clientY)});
function blocked(x,y){if(x<.5||y<.5||x>19||y>19)return true;return trees.some(t=>Math.hypot(t.x-x,t.y-y)<.57)}
function move(dx,dy){if(!blocked(player.x+dx,player.y))player.x+=dx;if(!blocked(player.x,player.y+dy))player.y+=dy}
function update(dt){time+=dt;if(state!=='play')return;invuln=Math.max(0,invuln-dt);cooldown=Math.max(0,cooldown-dt);pulse=Math.max(0,pulse-dt);toastTime-=dt;if(toastTime<=0)$('#toast').classList.remove('on');let sx=0,sy=0;if(keys.has('KeyW')||keys.has('ArrowUp'))sy--;if(keys.has('KeyS')||keys.has('ArrowDown'))sy++;if(keys.has('KeyA')||keys.has('ArrowLeft'))sx--;if(keys.has('KeyD')||keys.has('ArrowRight'))sx++;let dx=(sx+sy)*.707,dy=(sy-sx)*.707;if(target&&!sx&&!sy){dx=target.x-player.x;dy=target.y-player.y;if(Math.hypot(dx,dy)<.12){target=null;dx=dy=0}}let len=Math.hypot(dx,dy);walk=len>.05;if(walk){dx/=len;dy/=len;face=dx-dy>=0?1:-1;let ox=player.x,oy=player.y;move(dx*dt*2.3,dy*dt*2.3);if(target&&Math.hypot(ox-player.x,oy-player.y)<.001){target=null;toast('A crooked tree! Try the moonlit path.',2)}}for(const b of bats){let dist=Math.hypot(b.x-player.x,b.y-player.y);b.fear=Math.max(0,b.fear-dt);let tx=b.homeX+Math.sin(time*.8+b.phase)*.9,ty=b.homeY+Math.cos(time*.65+b.phase)*.9;if(dist<3&&!b.fear){tx=player.x;ty=player.y}if(b.fear){tx=b.homeX+(b.x-player.x)*2;ty=b.homeY+(b.y-player.y)*2}let nx=tx-b.x,ny=ty-b.y,l=Math.hypot(nx,ny);if(l>.05){b.x+=nx/l*dt*(b.fear?2:dist<3?1.2:.6);b.y+=ny/l*dt*(b.fear?2:dist<3?1.2:.6)}if(dist<.6&&!invuln&&!b.fear){heart--;hearts();invuln=2.2;b.fear=2;toast('Oops! A fluttery bump. Space to shoo the bats.',3);tone(240);if(heart<=0){player.x=2;player.y=3;heart=3;hearts();toast('Take a breath. Let’s try the trail again.',4)}}}
$('#glowStatus').textContent=cooldown>0?'✧ Recharging… '+Math.ceil(cooldown)+'s':'✧ Lantern ready';if(Math.hypot(player.x-17.5,player.y-17)<1){complete()}}
function complete(){tone(880,.5);modal('A thread of hope.','<p>Ara finds Ira’s ribbon caught beside the lantern gate.</p><p>“You came this way… I knew it. I’m going to find you, little sister.”</p><p style="color:#e5bf7f;font-style:italic">The first little stretch of woods is behind her.</p>',[{text:'Walk the woods again',primary:true,fn:begin},{text:'Return to title',fn:showMenu}],'CHAPTER ONE COMPLETE');pausedFrom='menu'}
function drawImage(img,x,y,w,h){if(img.complete&&img.naturalWidth)ctx.drawImage(img,x,y,w,h)}
function cover(img){if(!img.naturalWidth)return;let s=Math.max(W/img.width,H/img.height);ctx.drawImage(img,(W-img.width*s)/2,(H-img.height*s)/2,img.width*s,img.height*s)}
// Atlas source rectangles are set after the artwork is integrated.
const atlasRects={trees:[[0,0,450,602],[450,0,370,605],[820,0,400,613]],bats:[[1090,185,446,320],[20,605,430,390]],lantern:[575,604,228,405],ribbon:[934,655,590,355]};
function sprite(rect,x,y,w,h){let im=imgs.atlas;if(im.complete&&im.naturalWidth)ctx.drawImage(im,...rect,x,y,w,h)}
function diamond(x,y,fill){const p=project(x,y);ctx.fillStyle=fill;ctx.beginPath();ctx.moveTo(p.x,p.y-tile*.49);ctx.lineTo(p.x+tile,p.y);ctx.lineTo(p.x,p.y+tile*.49);ctx.lineTo(p.x-tile,p.y);ctx.closePath();ctx.fill()}
function render(){ctx.clearRect(0,0,W,H);if(state==='menu'||state==='comic'||(state==='dialog'&&pausedFrom==='menu')){cover(imgs.forest);if(!imgs.forest.naturalWidth){ctx.fillStyle='#142a32';ctx.fillRect(0,0,W,H)}fireflies();return}
ctx.fillStyle='#081721';ctx.fillRect(0,0,W,H);tile=W<700?39:54;camera.x=W*.5-(player.x-player.y)*tile;camera.y=H*.53-(player.x+player.y)*tile*.49;
let g=ctx.createRadialGradient(W*.5,H*.5,20,W*.5,H*.5,W*.75);g.addColorStop(0,'#254b4b');g.addColorStop(1,'#081721');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
for(let sum=0;sum<40;sum++)for(let x=0;x<20;x++){let y=sum-x;if(y<0||y>=20)continue;let p=project(x,y);if(p.x<-tile||p.x>W+tile||p.y<-tile||p.y>H+tile)continue;let trail=Math.abs(y-x-1.3*Math.sin(x*.45))<2;diamond(x,y,trail?['#53635b','#4c5c55','#59665a'][Math.floor(seed(x*43+y)*3)]:['#1b393b','#1e3b3b','#213f3c'][Math.floor(seed(x*43+y)*3)]);ctx.fillStyle=trail?'#a5a08038':'#7ba89320';for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(p.x+(seed(x*87+y+i)-.5)*tile,p.y+(seed(x+y*37+i)-.5)*tile*.5,2.5,1,0,0,7);ctx.fill()}}
let gate=project(17.5,17);ctx.strokeStyle='#b0d6ba';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(gate.x-35,gate.y+4);ctx.lineTo(gate.x-35,gate.y-80);ctx.quadraticCurveTo(gate.x,gate.y-115,gate.x+35,gate.y-80);ctx.lineTo(gate.x+35,gate.y+4);ctx.stroke();ctx.fillStyle='#d7c599';ctx.font='italic 15px Georgia';ctx.textAlign='center';ctx.fillText('The lantern gate',gate.x,gate.y-124);let lg=ctx.createRadialGradient(gate.x,gate.y-40,2,gate.x,gate.y-40,100);lg.addColorStop(0,'#f6d69077');lg.addColorStop(1,'#f6d69000');ctx.fillStyle=lg;ctx.fillRect(gate.x-100,gate.y-140,200,200);sprite(atlasRects.lantern,gate.x-24,gate.y-97,48,65);sprite(atlasRects.ribbon,gate.x+12,gate.y-12,45,27);
const ents=trees.map(t=>({depth:t.x+t.y,kind:'tree',t}));ents.push({depth:player.x+player.y,kind:'player'});bats.forEach(b=>ents.push({depth:b.x+b.y,kind:'bat',b}));ents.sort((a,b)=>a.depth-b.depth);for(const e of ents){if(e.kind==='tree'){let t=e.t,p=project(t.x,t.y),h=tile*3.3*t.size,w=h*.68;if(p.x<-w||p.x>W+w||p.y<-20||p.y>H+h)continue;let pp=project(player.x,player.y);ctx.globalAlpha=p.y>pp.y&&Math.abs(p.x-pp.x)<w*.48&&p.y-pp.y<h*.8?.28:1;sprite(atlasRects.trees[t.type],p.x-w/2,p.y-h,w,h);ctx.globalAlpha=1}else if(e.kind==='bat'){let b=e.b,p=project(b.x,b.y);ctx.fillStyle='#0003';ctx.beginPath();ctx.ellipse(p.x,p.y,15,5,0,0,7);ctx.fill();sprite(atlasRects.bats[reduced?0:Math.floor(time*8+b.phase)%2],p.x-34,p.y-68+(reduced?0:Math.sin(time*4+b.phase)*5),68,64)}else{let p=project(player.x,player.y);ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(p.x,p.y,22,8,0,0,7);ctx.fill();if(pulse>0){ctx.strokeStyle='#edd397'+Math.floor(pulse/.85*200).toString(16).padStart(2,'0');ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(p.x,p.y,35+(1-pulse/.85)*140,20+(1-pulse/.85)*70,0,0,7);ctx.stroke()}
let halo=ctx.createRadialGradient(p.x,p.y-30,5,p.x,p.y-30,95);halo.addColorStop(0,'#efd39135');halo.addColorStop(1,'#efd39100');ctx.fillStyle=halo;ctx.fillRect(p.x-100,p.y-130,200,200);ctx.save();ctx.translate(p.x,p.y-(walk&&!reduced?Math.abs(Math.sin(time*11))*5:0));ctx.scale(face,1);if(invuln&&Math.floor(time*12)%2)ctx.globalAlpha=.5;ctx.rotate(walk&&!reduced?Math.sin(time*11)*.055:0);drawImage(imgs.ara,-35,-94,70,98);ctx.restore();sprite(atlasRects.lantern,p.x+17,p.y-47,26,36)}}
if(target){let p=project(target.x,target.y);ctx.strokeStyle='#efd79caa';ctx.beginPath();ctx.ellipse(p.x,p.y,12,6,0,0,7);ctx.stroke()}fireflies();ctx.fillStyle='#a7c4b729';for(let i=0;i<4;i++){let y=H*.3+i*120;ctx.beginPath();ctx.ellipse(W*.5+Math.sin(time*.1+i)*130,y,W*.65,14,0,0,7);ctx.fill()}}
function fireflies(){for(let i=0;i<32;i++){let x=seed(i*7)*W+(reduced?0:Math.sin(time*.4+i)*22),y=seed(i*23+5)*H+(reduced?0:Math.cos(time*.3+i)*12);ctx.fillStyle='rgba(228,211,144,'+(.15+Math.sin(time*1.7+i)*.12)+')';ctx.beginPath();ctx.arc(x,y,1.5,0,7);ctx.fill()}}
function loop(ts){let dt=Math.min((ts-last)/1000,.04);last=ts;update(dt);render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
